(define (problem zoo-problem)
  (:domain zoo-world)
  (:objects t1 t2 t3 t4 t5 t6 t7 t8 t9 i1 i2 entrata recintoLama bar orsi gabbiaLeoni fossaCoccodrilli casaElefanti gabbiaTigri casaScimmie areaPicnicToilette riservaUccelli casaPiccoliMammiferi casaRettili)
  (:init 
         (connected t1 entrata) (connected t1 t2) (connected t1 bar)
         (connected t2 recintoLama) (connected t2 casaElefanti)
         (connected t3 orsi) (connected t3 gabbiaLeoni) (connected t3 entrata)
         (connected t3 t4) (connected t4 gabbiaLeoni)  
         (connected t4 fossaCoccodrilli) (connected t4 gabbiaTigri)
         (connected t4 t5)
         (connected t5 casaScimmie) (connected t5 i1)
         (connected t6 gabbiatigri)
         (connected t6 t7) (connected t6 t9) 
         (connected t7 t8) (connected t7 t9)
         (connected t8 casaPiccoliMammiferi) (connected t8 i2) 
         (connected t9 casaRettili)
         (connected i1 i2) (connected i1 casaElefanti)
         (connected i1 bar) 
         (connected i2 riservaUccelli)
         (connected i2 areaPicnicToilette)

         (visited entrata)
         (not-visited recintoLama)
         (not-visited bar)
         (not-visited orsi) 
         (not-visited gabbiaLeoni) 
         (not-visited fossaCoccodrilli) 
         (not-visited casaElefanti) 
         (not-visited gabbiaTigri) 
         (not-visited casaScimmie) 
         (not-visited areaPicnicToilette) 
         (not-visited riservaUccelli) 
         (not-visited casaPiccoliMammiferi) 
         (not-visited casaRettili)
         (not-visited t1) (not-visited t2) (not-visited t3) 
         (not-visited t4) (not-visited t5) (not-visited t6) 
         (not-visited t7) (not-visited t8) (not-visited t9)
         (not-visited I1) (not-visited I2) 
         (in entrata) (starting entrata) (finishing areaPicnicToilette)(not-complete))

  (:goal (and (visited casaElefanti) (visited gabbiaLeoni) (visited recintoLama) (visited bar) (visited orsi) (visited riservaUccelli) (visited areaPicnicToilette) (complete)))
  )