(define (problem zoo-problem1)
  (:domain zoo-world)
  (:objects t1 t2 t3 t4 t5 t6 t7 t8 t9 i1 i2 entrata lama bar orsi leoni coccodrilli elefanti tigri scimmie picnic uccelli mammiferi rettili)
  (:init 
         (erba t1 entrata) (erba t1 t2) (sentiero t1 bar)
         (erba t2 lama) (sentiero t2 elefanti)
         (sentiero t3 orsi) (sentiero t3 leoni) (sentiero t3 entrata)
         (sentiero t3 t4) (sentiero t4 leoni)  
         (erba t4 coccodrilli) (sentiero t4 tigri)
         (sentiero t4 t5)
         (erba t5 scimmie) (sentiero t5 i1)
         (sentiero t6 tigri)
         (sentiero t6 t7) (sentiero t6 t9) 
         (sentiero t7 t8) (sentiero t7 t9)
         (erba t8 mammiferi) (sentiero t8 i2) 
         (erba t9 rettili)
         (sentiero i1 i2) (sentiero i1 elefanti)
         (sentiero i1 bar) 
         (erba i2 uccelli)
         (sentiero i2 picnic)

         (not-visitedEdge t1 entrata) (not-visitedEdge t1 t2) (not-visitedEdge t1 bar)
         (not-visitedEdge t2 lama) (not-visitedEdge t2 elefanti)
         (not-visitedEdge t3 orsi) (not-visitedEdge t3 leoni) (not-visitedEdge t3 entrata)
         (not-visitedEdge t3 t4) (not-visitedEdge t4 leoni)  
         (not-visitedEdge t4 coccodrilli) (not-visitedEdge t4 tigri)
         (not-visitedEdge t4 t5)
         (not-visitedEdge t5 scimmie) (not-visitedEdge t5 i1)
         (not-visitedEdge t6 tigri)
         (not-visitedEdge t6 t7) (not-visitedEdge t6 t9) 
         (not-visitedEdge t7 t8) (not-visitedEdge t7 t9)
         (not-visitedEdge t8 mammiferi) (not-visitedEdge t8 i2) 
         (not-visitedEdge t9 rettili)
         (not-visitedEdge i1 i2) (not-visitedEdge i1 elefanti)
         (not-visitedEdge i1 bar) 
         (not-visitedEdge i2 uccelli)
         (not-visitedEdge i2 picnic)



         (visited entrata)
         (not-visited lama)
         (not-visited bar)
         (not-visited orsi) 
         (not-visited leoni) 
         (not-visited coccodrilli) 
         (not-visited elefanti) 
         (not-visited tigri) 
         (not-visited scimmie) 
         (not-visited picnic) 
         (not-visited uccelli) 
         (not-visited mammiferi) 
         (not-visited rettili)
         (not-visited t1) (not-visited t2) (not-visited t3) 
         (not-visited t4) (not-visited t5) (not-visited t6) 
         (not-visited t7) (not-visited t8) (not-visited t9)
         (not-visited i1) (not-visited i2) 
         (in entrata) (starting entrata) (finishing picnic) (not-complete))

  (:goal (and (visited elefanti) (visited leoni) (visited lama) (visited bar) (visited orsi) (visited uccelli) )) ;;(visited picnic) (complete)
)
