(define (problem zoo-problem1)
  (:domain zoo-world)
  (:objects t0 t1 t2 t3 t4 t5 t6 t7 t8 t9 i0 i1 entrata lama bar orsi leoni coccodrilli elefanti tigri scimmie picnic uccelli mammiferi rettili)
  (:init

        (erba t0 entrata) (erba entrata t0)
        (erba t0 t1) (erba t1 t0)
        (sentiero t0 bar) (sentiero bar t0)
        (erba t1 lama) (erba lama t1)
        (sentiero t1 elefanti) (sentiero elefanti t1)
        (erba t2 orsi) (erba orsi t2)
        (sentiero t2 leoni) (sentiero leoni t2)
        (sentiero t2 entrata) (sentiero entrata t2)
        (sentiero t2 t3) (sentiero t3 t2)
        (sentiero t3 leoni) (sentiero leoni t3)
        (erba t3 coccodrilli) (erba coccodrilli t3)
        (sentiero t3 t5) (sentiero t5 t3)
        (sentiero t3 t4) (sentiero t4 t3)
        (erba t4 scimmie) (erba scimmie t4)
        (sentiero t4 i0) (sentiero i0 t4)
        (erba t5 tigri) (erba tigri t5)
        (sentiero t6 t5) (sentiero t5 t6)
        (sentiero t6 t7) (sentiero t7 t6)
        (sentiero t6 t9) (sentiero t9 t6)
        (sentiero t7 t8) (sentiero t8 t7)
        (sentiero t7 t9) (sentiero t9 t7)
        (erba t8 mammiferi) (erba mammiferi t8)
        (sentiero t8 i1) (sentiero i1 t8)
        (erba t9 rettili) (erba rettili t9)
        (sentiero i0 i1) (sentiero i1 i0)
        (sentiero i0 elefanti) (sentiero elefanti i0)
        (sentiero i0 bar) (sentiero bar i0)
        (erba i1 uccelli) (erba uccelli i1)
        (sentiero i1 picnic) (sentiero picnic i1)

         (not-visitedEdge t0 entrata) (not-visitedEdge entrata t0)
         (not-visitedEdge t0 t1) (not-visitedEdge t1 t0)
         (not-visitedEdge t0 bar) (not-visitedEdge bar t0)
         (not-visitedEdge t1 lama) (not-visitedEdge lama t1)
         (not-visitedEdge t1 elefanti) (not-visitedEdge elefanti t1)
         (not-visitedEdge t2 orsi) (not-visitedEdge orsi t2)
         (not-visitedEdge t2 leoni) (not-visitedEdge leoni t2)
         (not-visitedEdge t2 entrata) (not-visitedEdge entrata t2)
         (not-visitedEdge t2 t3) (not-visitedEdge t3 t2)
         (not-visitedEdge t3 leoni) (not-visitedEdge leoni t3)
         (not-visitedEdge t3 coccodrilli) (not-visitedEdge coccodrilli t3)
         (not-visitedEdge t3 t5) (not-visitedEdge t5 t3)
         (not-visitedEdge t3 t4) (not-visitedEdge t4 t3)
         (not-visitedEdge t4 scimmie) (not-visitedEdge scimmie t4)
         (not-visitedEdge t4 i0) (not-visitedEdge i0 t4)
         (not-visitedEdge t5 tigri) (not-visitedEdge tigri t5)
         (not-visitedEdge t6 t5) (not-visitedEdge t5 t6)
         (not-visitedEdge t6 t7) (not-visitedEdge t7 t6)
         (not-visitedEdge t6 t9) (not-visitedEdge t9 t6)
         (not-visitedEdge t7 t8) (not-visitedEdge t8 t7)
         (not-visitedEdge t7 t9) (not-visitedEdge t9 t7)
         (not-visitedEdge t8 mammiferi) (not-visitedEdge mammiferi t8)
         (not-visitedEdge t8 i1) (not-visitedEdge i1 t8)
         (not-visitedEdge t9 rettili) (not-visitedEdge rettili t9)
         (not-visitedEdge i0 i1) (not-visitedEdge i1 i0)
         (not-visitedEdge i0 elefanti) (not-visitedEdge elefanti i0)
         (not-visitedEdge i0 bar) (not-visitedEdge bar i0)
         (not-visitedEdge i1 uccelli) (not-visitedEdge uccelli i1)
         (not-visitedEdge i1 picnic) (not-visitedEdge picnic i1)

         (visited entrata)
         (not-visited lama)
         (not-visited bar)
         (not-visited orsi)
         (not-visited leoni)
         (not-visited coccodrilli)
         (not-visited elefanti)
         (not-visited tigri)
         (not-visited scimmie)
         (not-visited picnic)
         (not-visited uccelli)
         (not-visited mammiferi)
         (not-visited rettili)
         (not-visited t0) (not-visited t1) (not-visited t2)
         (not-visited t3) (not-visited t4) (not-visited t5)
         (not-visited t6) (not-visited t7) (not-visited t8) (not-visited t9)
         (not-visited i0) (not-visited i1)
         (in entrata) (starting entrata) (finishing picnic) (not-complete))

  (:goal (and (visited elefanti) (visited leoni) (visited lama) (visited bar) (visited orsi) (visited uccelli) (visited picnic) (complete)))
)
