(define (problem zoo-problem1)
  (:domain zooworld)
  (:objects t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 i1 i2 entrata lama bar orsi leoni coccodrilli elefanti tigri scimmie picnic uccelli mammiferi rettili)
  (:init (erba t1 entrata) (erba entrata t1)
        (erba t1 t2) (erba t2 t1)
        (sentiero t1 bar) (sentiero bar t1)
        (erba t2 lama) (erba lama t2)
        (sentiero t2 elefanti) (sentiero elefanti t2)
        (erba t3 orsi) (erba orsi t3)
        (sentiero t3 leoni) (sentiero leoni t3)
        (sentiero t3 entrata) (sentiero entrata t3)
        (sentiero t3 t4) (sentiero t4 t3)
        (sentiero t4 leoni) (sentiero leoni t4)
        (erba t4 coccodrilli) (erba coccodrilli t4)
        (sentiero t4 t6) (sentiero t6 t4)
        (sentiero t4 t5) (sentiero t5 t4)
        (erba t5 scimmie) (erba scimmie t5)
        (sentiero t5 i1) (sentiero i1 t5)
        (erba t6 tigri) (erba tigri t6)
        (sentiero t7 t6) (sentiero t6 t7)
        (sentiero t7 t8) (sentiero t8 t7)
        (sentiero t7 t10) (sentiero t10 t7)
        (sentiero t8 t9) (sentiero t9 t8)
        (sentiero t8 t10) (sentiero t10 t8)
        (erba t9 mammiferi) (erba mammiferi t9)
        (sentiero t9 i2) (sentiero i2 t9)
        (erba t10 rettili) (erba rettili t10)
        (sentiero i1 i2) (sentiero i2 i1)
        (sentiero i1 elefanti) (sentiero elefanti i1)
        (sentiero i1 bar) (sentiero bar i1)
        (erba i2 uccelli) (erba uccelli i2)
        (sentiero i2 picnic) (sentiero picnic i2)        

         (not-visitedEdge t1 entrata) (not-visitedEdge entrata t1)
         (not-visitedEdge t1 t2) (not-visitedEdge t2 t1)
         (not-visitedEdge t1 bar) (not-visitedEdge bar t1)
         (not-visitedEdge t2 lama) (not-visitedEdge lama t2)
         (not-visitedEdge t2 elefanti) (not-visitedEdge elefanti t2)
         (not-visitedEdge t3 orsi) (not-visitedEdge orsi t3)
         (not-visitedEdge t3 leoni) (not-visitedEdge leoni t3)
         (not-visitedEdge t3 entrata) (not-visitedEdge entrata t3)
         (not-visitedEdge t3 t4) (not-visitedEdge t4 t3)
         (not-visitedEdge t4 leoni) (not-visitedEdge leoni t4)
         (not-visitedEdge t4 coccodrilli) (not-visitedEdge coccodrilli t4)
         (not-visitedEdge t4 t6) (not-visitedEdge t6 t4)
         (not-visitedEdge t4 t5) (not-visitedEdge t5 t4)
         (not-visitedEdge t5 scimmie) (not-visitedEdge scimmie t5)
         (not-visitedEdge t5 i1) (not-visitedEdge i1 t5)
         (not-visitedEdge t6 tigri) (not-visitedEdge tigri t6)
         (not-visitedEdge t7 t6) (not-visitedEdge t6 t7)
         (not-visitedEdge t7 t8) (not-visitedEdge t8 t7)
         (not-visitedEdge t7 t10) (not-visitedEdge t10 t7)
         (not-visitedEdge t8 t9) (not-visitedEdge t9 t8)
         (not-visitedEdge t8 t10) (not-visitedEdge t10 t8)
         (not-visitedEdge t9 mammiferi) (not-visitedEdge mammiferi t9)
         (not-visitedEdge t9 i2) (not-visitedEdge i2 t9)
         (not-visitedEdge t10 rettili) (not-visitedEdge rettili t10)
         (not-visitedEdge i1 i2) (not-visitedEdge i2 i1)
         (not-visitedEdge i1 elefanti) (not-visitedEdge elefanti i1)
         (not-visitedEdge i1 bar) (not-visitedEdge bar i1)
         (not-visitedEdge i2 uccelli) (not-visitedEdge uccelli i2)
         (not-visitedEdge i2 picnic) (not-visitedEdge picnic i2)

         (visited entrata)
         (not-visited lama)
         (not-visited bar)
         (not-visited orsi)
         (not-visited leoni)
         (not-visited coccodrilli)
         (not-visited elefanti)
         (not-visited tigri)
         (not-visited scimmie)
         (not-visited picnic)
         (not-visited uccelli)
         (not-visited mammiferi)
         (not-visited rettili)
         (not-visited t1) (not-visited t2) (not-visited t3)
         (not-visited t4) (not-visited t5) (not-visited t6)
         (not-visited t7) (not-visited t8) (not-visited t9) (not-visited t10)
         (not-visited i1) (not-visited i2)
         (in entrata) (starting entrata) (finishing picnic) (not-complete))

  (:goal (and (visited elefanti) (visited leoni) (visited lama) (visited bar) (visited orsi) (visited uccelli) (visited picnic) (complete)))
)
