(define (problem zoo)
(:domain test)
(:objects visitor camel1 camel2 camel3 entrance n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 monkey lama eleph bar reptile bear lion tiger smammal wc croc bird)
(:init
	(visitor visitor)
	(mobile visitor)
	(able-to-climb visitor)
	(camel camel1)
	(camel camel2)
	(camel camel3)

	(at visitor entrance)
	(at camel1 bar)
	(at camel2 n5)
	(at camel3 n7)

	(to-discover entrance)
	(to-discover n1)
	(to-discover n2)
	(to-discover n3)
	(to-discover n4)
	(to-discover n5)
	(to-discover n6)
	(to-discover n7)
	(to-discover n8)
	(to-discover n9)
	(to-discover n10)
	(to-discover monkey)
	(to-discover lama)
	(to-discover eleph)
	(to-discover bar)
	(to-discover reptile)
	(to-discover bear)
	(to-discover lion)
	(to-discover tiger)
	(to-discover smammal)
	(to-discover wc)
	(to-discover croc)
	(to-discover bird)

	(shadow entrance n1) (shadow n1 entrance) (able-to-walk entrance n1) (able-to-walk n1 entrance)
	(shadow n1 n2) (shadow n2 n1) (able-to-walk n1 n2) (able-to-walk n2 n1)
	(shadow n2 monkey) (shadow monkey n2) (able-to-walk n2 monkey) (able-to-walk monkey n2)
	(shadow n3 eleph) (shadow eleph n3) (able-to-walk n3 eleph) (able-to-walk eleph n3)
	(shadow n4 bar) (shadow bar n4) (able-to-walk n4 bar) (able-to-walk bar n4)
	(shadow n7 tiger) (shadow tiger n7) (able-to-walk n7 tiger) (able-to-walk tiger n7)
	(shadow n8 smammal) (shadow smammal n8) (able-to-walk n8 smammal) (able-to-walk smammal n8)
	(shadow n9 wc) (shadow wc n9) (able-to-walk n9 wc) (able-to-walk wc n9)
	(shadow n10 croc) (shadow croc n10) (able-to-walk n10 croc) (able-to-walk croc n10)
	(road entrance n3) (road n3 entrance) (able-to-walk entrance n3) (able-to-walk n3 entrance)
	(road n1 lama) (road lama n1) (able-to-walk n1 lama) (able-to-walk lama n1)
	(road n2 bear) (road bear n2) (able-to-walk n2 bear) (able-to-walk bear n2)
	(road n3 n4) (road n4 n3) (able-to-walk n3 n4) (able-to-walk n4 n3)
	(road n3 reptile) (road reptile n3) (able-to-walk n3 reptile) (able-to-walk reptile n3)
	(road n4 n5) (road n5 n4) (able-to-walk n4 n5) (able-to-walk n5 n4)
	(road n4 n7) (road n7 n4) (able-to-walk n4 n7) (able-to-walk n7 n4)
	(road n5 reptile) (road reptile n5) (able-to-walk n5 reptile) (able-to-walk reptile n5)
	(road n5 lion) (road lion n5) (able-to-walk n5 lion) (able-to-walk lion n5)
	(road n6 n7) (road n7 n6) (able-to-walk n6 n7) (able-to-walk n7 n6)
	(road n6 bear) (road bear n6) (able-to-walk n6 bear) (able-to-walk bear n6)
	(road n8 n9) (road n9 n8) (able-to-walk n8 n9) (able-to-walk n9 n8)
	(road n8 bird) (road bird n8) (able-to-walk n8 bird) (able-to-walk bird n8)
	(road n9 n10) (road n10 n9) (able-to-walk n9 n10) (able-to-walk n10 n9)
	(road n9 lion) (road lion n9) (able-to-walk n9 lion) (able-to-walk lion n9)
	(road n10 lion) (road lion n10) (able-to-walk n10 lion) (able-to-walk lion n10)
	(camelroad n6 n8) (camelroad n8 n6) (able-to-ride n6 n8) (able-to-ride n8 n6)
	(camelroad n6 lama) (camelroad lama n6) (able-to-ride n6 lama) (able-to-ride lama n6))
(:goal (and
	(not (to-discover lion))
	(not (to-discover eleph))
	(not (to-discover monkey))
	(not (to-discover bear))
	(at visitor croc)))
)